#!/usr/bin/env ruby
# encoding: UTF-8

# load Rails env
require ::File.expand_path('../../config/environment',  __FILE__)

# resolve bin path, ignoring symlinks
require "pathname"
bin_file = Pathname.new(__FILE__).realpath

# add self to libpath
$:.unshift File.expand_path("../../lib", bin_file)

Delayed::Job.last.invoke_job
